<a href="https://colab.research.google.com/github/Leslyndizeye/Inclass-activity-neuron/blob/main/Live_coding_Neuron_Ganza_Owen_Yhaan_%26_Ndizeye_Lesly_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ganza Owen Yhaan & Ndizeye Lesly

Write a class Neuron that defines a single neuron performing binary classification:

class constructor: def __init__(self, nx):
nx is the number of input features to the neuron
If nx is not an integer, raise a TypeError with the exception: nx must be an integer
If nx is less than 1, raise a ValueError with the exception: nx must be a positive integer
All exceptions should be raised in the order listed above
Public instance attributes:
W: The weights vector for the neuron. Upon instantiation, it should be initialized using a random normal distribution.
b: The bias for the neuron. Upon instantiation, it should be initialized to 0.
A: The activated output of the neuron (prediction). Upon instantiation, it should be initialized to 0.

In [18]:
import pandas as pd
import numpy as np

In [19]:
data = pd.read_csv('https://gist.githubusercontent.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6/raw/92200bc0a673d5ce2110aaad4544ed6c4010f687/pokemon.csv')
data.head(5)

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [20]:
new_data = pd.get_dummies(data)
new_data.head(5)

#  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  \
0  1    318  45      49       49       65       65     45           1   
1  2    405  60      62       63       80       80     60           1   
2  3    525  80      82       83      100      100     80           1   
3  3    625  80     100      123      122      120     80           1   
4  4    309  39      52       43       60       50     65           1   

   Legendary  ...  Type 2_Ghost  Type 2_Grass  Type 2_Ground  Type 2_Ice  \
0      False  ...         False         False          False       False   
1      False  ...         False         False          False       False   
2      False  ...         False         False          False       False   
3      False  ...         False         False          False       False   
4      False  ...         False         False          False       False   

   Type 2_Normal  Type 2_Poison  Type 2_Psychic  Type 2_Rock  Type 2_Steel  \
0          False           True           False        False         False   
1          False           True           False        False         False   
2          False           True           False        False         False   
3          False           True           False        False         False   
4          False          False           False        False         False   

   Type 2_Water  
0         False  
1         False  
2         False  
3         False  
4         False  

[5 rows x 846 columns]

In [21]:
input = np.array(new_data.drop(['Legendary'], axis = 1), dtype = 'float')
print(input)

[[  1. 318.  45. ...   0.   0.   0.]
 [  2. 405.  60. ...   0.   0.   0.]
 [  3. 525.  80. ...   0.   0.   0.]
 ...
 [720. 600.  80. ...   0.   0.   0.]
 [720. 680.  80. ...   0.   0.   0.]
 [721. 600.  80. ...   0.   0.   1.]]


In [22]:
print(input.shape)

(800, 845)


In [23]:
nx = input.shape[1]

In [24]:
class Neuron:
    def __init__(self, nx):
        if not isinstance(nx, int):
            raise TypeError("nx must be an integer")
        if nx < 1:
            raise ValueError("nx must be a positive integer")

        self.W = np.random.randn(1, nx)
        self.b = 0.0
        self.A = 0.0

    def lin_reg(self, X):
      # Calculate z using linear equation mx = b
      return np.dot(self.W, X) + self.b

    def sigmoid(self, Z):
      # Squeeze the output to be btn 0-1
      return 1 / (1 + np.exp(-Z))

    def forward_propagate(self, X):
      Z = self.lin_reg(X)
      self.A = self.sigmoid(Z)
      return self.A

In [25]:
# Transpose input for compatibility with neuron computation
X_test = input.T
# Reshape labels to match expected dimensions (1, number of examples)
Y_test = np.array(new_data['Legendary'].astype(int)).reshape(1, X_test.shape[1])

# Determine number of test examples
num_examples = X_test.shape[1]

print("--- Preparing Test Data ---")
print(f"X_test shape (features x examples): {X_test.shape}")
print(f"Y_test shape (1 x examples): {Y_test.shape}")
print(f"Input feature count (nx): {nx}")
print(f"Total number of test examples (m): {num_examples}")
print("-" * 40)

# Step 2: Initialize Neuron
try:
    print("--- Creating Neuron Instance ---")
    my_neuron = Neuron(nx=nx)  # Assumes nx is predefined
    print("Neuron created successfully.")
    print(f"Initial weights shape: {my_neuron.W.shape}")
    print(f"Initial bias value: {my_neuron.b}")
    print(f"Initial activation value: {my_neuron.A}")
    print("-" * 40)

    # Step 3: Generate predictions using forward propagation
    print("--- Running Forward Propagation ---")
    A_predictions = my_neuron.forward_propagate(X_test)
    print(f"Prediction output shape: {A_predictions.shape}")
    print("Preview of first 5 predicted probabilities:")
    print(A_predictions[0, :5])
    print("-" * 40)

    # Step 4: Convert probabilities into binary output using threshold
    print("--- Converting to Binary Predictions ---")
    binary_preds = (A_predictions >= 0.5).astype(int)
    print("First 5 predicted binary values:")
    print(binary_preds[0, :5])
    print("First 5 actual label values:")
    print(Y_test[0, :5])
    print("-" * 40)

    # Step 5: Evaluate basic prediction accuracy (prior to training)
    print("--- Evaluating Initial Accuracy ---")
    accuracy = np.mean(binary_preds == Y_test) * 100
    print(f"Untrained neuron accuracy: {accuracy:.2f}%")

except TypeError as te:
    print(f"TypeError encountered: {te}")
except ValueError as ve:
    print(f"ValueError encountered: {ve}")
except Exception as e:
    print(f"Unexpected error occurred: {e}")


--- Preparing Test Data ---
X_test shape (features x examples): (845, 800)
Y_test shape (1 x examples): (1, 800)
Input feature count (nx): 845
Total number of test examples (m): 800
----------------------------------------
--- Creating Neuron Instance ---
Neuron created successfully.
Initial weights shape: (1, 845)
Initial bias value: 0.0
Initial activation value: 0.0
----------------------------------------
--- Running Forward Propagation ---
Prediction output shape: (1, 800)
Preview of first 5 predicted probabilities:
[1. 1. 1. 1. 1.]
----------------------------------------
--- Converting to Binary Predictions ---
First 5 predicted binary values:
[1 1 1 1 1]
First 5 actual label values:
[0 0 0 0 0]
----------------------------------------
--- Evaluating Initial Accuracy ---
Untrained neuron accuracy: 8.12%
